### PR TITLE
RetryPolicy fixes

### LINKED ISSUE #448: Combining RetryStrategies broken in M10?
Hey Folks, 
thanks for your great work on this library so far 👍 
After updating to `1.0.0-M10`, I was trying out the new `RetryStrategy` from #402 and stumbled on this weird behaviour when combining strategies, being unable to combine delay with a maximum amount of retries.

```scala
import akka.actor.ActorSystem
import akka.stream.ActorMaterializer
import akka.stream.scaladsl.{Sink, Source}
import com.amazonaws.services.dynamodbv2.model._
import org.scalatest.{Assertion, BeforeAndAfterAll, FreeSpec}
import org.scanamo.ops.retrypolicy.{RetryPolicy, WithRetry}

import scala.concurrent.Await
import scala.concurrent.duration._
import scala.util.control.NonFatal

class ScanamoIssue extends FreeSpec with BeforeAndAfterAll with WithRetry {

  implicit val actorSystem: ActorSystem        = ActorSystem()
  implicit val materializer: ActorMaterializer = ActorMaterializer()

  override protected def afterAll(): Unit = {
    materializer.shutdown()
    Await.ready(actorSystem.terminate(), 10.seconds)
  }

  private val tries  = 5
  private val delay  = 50.millis
  private val factor = 2.0

  private def testcase(policy: RetryPolicy): Assertion = {
    val errors = Await.result(
      retry(Source.failed(new LimitExceededException("Limit Exceeded")), policy)
        .recover {
          case NonFatal(t) => t
        }
        .runWith(Sink.seq),
      5.seconds
    )
    assert(errors.size == 1)
  }

  private def testcaseWithDelay(policy: RetryPolicy) = {
    val minDelay = tries * delay.toMillis
    val start = System.currentTimeMillis()
    testcase(policy)
    val stop = System.currentTimeMillis()
    assert(stop - start > minDelay)
  }

  "Retry Policies should terminate" - {
    "Plain maximum" in testcase(RetryPolicy.Max(tries))
    "Constant delay AND maximum" in testcaseWithDelay(RetryPolicy.Max(tries) && RetryPolicy.Constant(delay))
    "Linear delay AND maximum" in testcaseWithDelay(RetryPolicy.Max(tries) && RetryPolicy.Linear(delay, factor))
    "Exponential delay AND maximum" in testcase(RetryPolicy.Max(tries) && RetryPolicy.Exponential(delay, factor))
    "Constant delay OR maximum" in testcaseWithDelay(RetryPolicy.Max(tries) || RetryPolicy.Constant(delay))
    "Linear delay OR maximum" in testcaseWithDelay(RetryPolicy.Max(tries) || RetryPolicy.Linear(delay, factor))
    "Exponential delay OR maximum" in testcase(RetryPolicy.Max(tries) || RetryPolicy.Exponential(delay, factor))
  }
}
```
I'd expect all of these tests to pass, but only the first one does. 
As far as I see it, there's currently no way of combining limited retries with any sort of delay, even though the API suggests this. 

Am I missing something here?

Cheers,
Joe

### PR DESCRIPTION
**Pull request by regiskuckaertz**
Closes #448 

Also steals tests from the ticket.

Fixes:
- Max bottoms out at 0 and never goes below
- switch `Duration` for `FiniteDuration` (`Never ~ Duration.Inf`)
- Fixes exponential delay calculation
- adds constructors to guarantee correctness
- proper introduction of a delay in the stream algebra

### CODE REVIEW

File: alpakka/src/main/scala/org/scanamo/ops/retrypolicy/RetryPolicy.scala [hunk 1]
```diff
@@ -2,53 +2,82 @@ package org.scanamo.ops.retrypolicy
...
-    case Or(thisPolicy, thatPolicy)  => Math.min(thisPolicy.delay, thatPolicy.delay)
-    case _                           => 0
+  final def delay: Duration = self match {
+    case Constant(retryDelay)               => retryDelay
+    case Linear(retryDelay, n)              => retryDelay * n.toDouble
+    case Exponential(retryDelay, factor, n) => retryDelay * Math.pow(factor, n.toDouble)
+    case And(thisPolicy, thatPolicy) =>
+      val d1 = thisPolicy.delay
+      val d2 = thatPolicy.delay
+      if (d1 >= d2) d1 else d2
```
Comment (TBonnin) [inline alpakka/src/main/scala/org/scanamo/ops/retrypolicy/RetryPolicy.scala]: `Duration` has `min/max` function: 

```
case And(thisPolicy, thatPolicy) => thisPolicy.delay.max(thatPolicy.delay)
```

Comment (regiskuckaertz) [reply alpakka/src/main/scala/org/scanamo/ops/retrypolicy/RetryPolicy.scala]: Oh great!
